version: "3.9"
services:
  game-digger:
    build: .
    container_name: game-digger
    image: game-digger:latest
    env_file:
      - common.env
    restart: always
  postgres:
    container_name: postgres-gd
    image: postgres:latest
    volumes:
      - /var/lib/postgres-data-gd:/var/lib/postgresql/data
    ports:
      - 5433:5432
    env_file:
      - common.env
    restart: always
  grafana:
    container_name: grafana
    image: grafana/grafana-oss:latest
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 5050:3000
    user: '104'

volumes:
  grafana-storage:
    external: true
