version: "3.9"
services:
  game-digger:
    build: .
    container_name: game-digger
    env_file:
      - common.env
    restart: always
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - common.env
    restart: always
