{
 "title": "GameDigger - Use stats",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "TimePeriod",
    "query": "1m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Average No. Requests / Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(idx)\r\nFROM gd.requests\r\nGROUP BY user_idx"
    }
   ]
  },
  {
   "title": "Avg. Ratings / User",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(idx)\r\nFROM gd.ratings\r\nGROUP BY user_idx"
    }
   ]
  },
  {
   "title": "Users / Platform",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(idx) as value,\n  platform as metric\nFROM\n  gd.users\nGROUP BY\n  platform"
    }
   ]
  },
  {
   "title": "Requests / time-periods",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(request_time, '$TimePeriod') AS \"time\",\n  COUNT(idx) AS \"No. Requests\"\nFROM gd.requests\nWHERE\n  $__timeFilter(request_time)\nGROUP BY $__timeGroup(request_time, '$TimePeriod')\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Requests over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  request_time AS \"time\",\n  idx AS \"RequestNo.\"\nFROM gd.requests\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Games in DB",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(idx)\nFROM gd.games"
    }
   ]
  }
 ]
}